### ISSUE TITLE
The nx typedoc plugin caching seems broken

### ISSUE THREAD

**Issue by Fuco1** [enio-ireland/enio#45]
When I run the typedoc target and then delete the output in the `docs`, the next run "uses cache" but no output is provided.

To fix this, the target in `project.json` must include `"outputs"` key with the directory where the output is created, so that nx knows how to restore it from cache.

```
"typedoc": {
      "executor": "@enio.ai/typedoc:typedoc",
      "outputs": ["docs/libs/ds"],                         //// << add this
      "options": {
        "options": "libs/ds/typedoc.json"
      },
      "configurations": {}
    }
```

**Comment by AndrewRedican** [comment]
@Fuco1 thanks for your feedback. I'll include this to the generated configuration shorty.
