### ISSUE TITLE
Typedoc plugin - Monorepo path exposed in docs

### ISSUE THREAD

**Issue by Amgelo563** [enio-ireland/enio#83]
Hi, I'm currently experiencing the exact issue described [here](https://github.com/TypeStrong/typedoc/issues/642) when using the Typedoc plugin. For some reason, Typedoc seems to grab the entire root path to generate instead of the `src` path of my Nx repository, as expected. The image can describe better the issue:

![image](https://user-images.githubusercontent.com/61554601/227248721-35da4d6d-2ecd-4d1d-8f2f-1cc1ff2ceee8.png)

This is my `typedoc.json`, it's pretty much the default one, I just touched a few settings trying to solve the issue but I think it's back now to default: https://pastebin.com/YyRJBjDs

These are my `tsconfig.base.json`, `tsconfig.json` and `tsconfig.lib.json`, if useful: https://pastebin.com/nFVMPvjP

I can confirm that the [workaround](https://github.com/TypeStrong/typedoc/issues/642#issuecomment-606316381) mentioned in the original issue works, but as others mentioned there, it also removes paths completely, which is something that I don't really want.

Others mentioned that "Installing typedoc locally in the project dir solved the issue", but I'm not sure how to do that with Nx since it installs libraries to the whole project and then each monorepo uses them as needed.

I would be very grateful with any guidance or recommendations, thanks.

**Comment by Amgelo563** [comment]
Additionally, it seems like plugins using copy operations don't work as intended. Here's an error from `typedoc-plugin-mtos` when trying to use its custom css/js feature, and a similar error happened when trying to use a favicon with a relative path from `typedoc-plugin-extras`.
```
TypeDoc exiting with unexpected error:
Error: ENOENT: no such file or directory, copyfile 'assets/custom.js' -> 'D:\Software\Code\Active\nx-nyx\packages\core\D:\Software\Code\Active\nx-nyx\docs\packages\core\assets\custom.js'
    at Object.copyFileSync (node:fs:2802:3)
    at Object.onRenderFinished (D:\Software\Code\Active\nx-nyx\node_modules\.pnpm\typedoc-plugin-mtos@0.8.0_typedoc@0.23.28\node_modules\typedoc-plugin-mtos\dist\index.js:39:12)
    at Renderer.<anonymous> (D:\Software\Code\Active\nx-nyx\node_modules\.pnpm\typedoc@0.23.28_typescript@4.9.5\node_modules\typedoc\dist\lib\utils\events.js:150:22)
    at Renderer.<anonymous> (D:\Software\Code\Active\nx-nyx\node_modules\.pnpm\typedoc@0.23.28_typescript@4.9.5\node_modules\typedoc\dist\lib\utils\events.js:26:25)
    at triggerEvents (D:\Software\Code\Active\nx-nyx\node_modules\.pnpm\typedoc@0.23.28_typescript@4.9.5\node_modules\typedoc\dist\lib\utils\events.js:191:43)
    at triggerApi (D:\Software\Code\Active\nx-nyx\node_modules\.pnpm\typedoc@0.23.28_typescript@4.9.5\node_modules\typedoc\dist\lib\utils\events.js:167:13)
    at eventsApi (D:\Software\Code\Active\nx-nyx\node_modules\.pnpm\typedoc@0.23.28_typescript@4.9.5\node_modules\typedoc\dist\lib\utils\events.js:60:18)
    at Renderer.trigger (D:\Software\Code\Active\nx-nyx\node_modules\.pnpm\typedoc@0.23.28_typescript@4.9.5\node_modules\typedoc\dist\lib\utils\events.js:389:13)
    at Renderer.render (D:\Software\Code\Active\nx-nyx\node_modules\.pnpm\typedoc@0.23.28_typescript@4.9.5\node_modules\typedoc\dist\lib\output\renderer.js:161:18)
    at async Application.generateDocs (D:\Software\Code\Active\nx-nyx\node_modules\.pnpm\typedoc@0.23.28_typescript@4.9.5\node_modules\typedoc\dist\lib\application.js:287:9) {
  errno: -4058,
  syscall: 'copyfile',
  code: 'ENOENT',
  path: 'assets/custom.js',
  dest: 'D:\\Software\\Code\\Active\\nx-nyx\\packages\\core\\D:\\Software\\Code\\Active\\nx-nyx\\docs\\packages\\core\\assets\\custom.js'
}
```
The errored codeblock (on `typedoc-plugin-mtos`'s code) is:
```js
function onRenderFinished() {
    const options = this.options();
    const workingDir = process.cwd();
    const outDir = options.outDir || "./docs";
    if (options.customJs)
        fs.copyFileSync(options.customJs, path.join(workingDir, outDir, "assets", path.basename(options.customJs)));
```
Specifically that last line. I'm assuming that `workingDir` is `D:\\Software\\Code\\Active\\nx-nyx\\packages\\core`, and `outDir` is `D:\\Software\\Code\\Active\\nx-nyx\\docs\\packages\\core` which causes the error.

**Comment by AndrewRedican** [comment]
@Amgelo563,

I think I understand what you need.

You probably need a package.json file in the project where you intend to have typedoc set up, so that it knows how to pick the correct directory (not the monorepo workspace directory).

Initially, I thought Nx kept project's package.json separate. Until I started creating app type projects I realized the only projects that get distinct package.json file is libs or "packages". This is a major dissapointment/dissagreement I have with Nx which you can read about here. https://github.com/nrwl/nx/issues/15360

I don't know the specific instructions to what you need, but this is what I would do in your shoes.

1. Find an example of a lib project that has it's own package.json.
2. If you don't have any there are a few plugins/generators that create libraries and will set up the package.json for it.
3. Simply add a package.json to any project that is missing it, and typedoc and other relevant project dependencies in there, and take note of any configuration that is different in the project.json. I suspect the project.json ultimately indicates to which package.json to look at, or,.. it could be the case that it simply looks to the closes package.json if it doesn't find any it might go all the way to the workspace root.

Last but not least, if you need me to update the generator or add some additional parameter, so long as it is officially supported by Typedoc I am more than happy to update that generator.

Good luck and let me know how it goes.

**Comment by Amgelo563** [comment]
Hi, thanks for the reply.

I didn't specify this, the project that I'm whose typedoc I'm trying to generate is a package, so it had a `package.json` already. Specifically like this:
![image](https://user-images.githubusercontent.com/61554601/230199423-99b9605f-e128-4d07-9c79-fcab851d3953.png)
Old contents of the mentioned `package.json`:
```json
{
  "name": "@nyx/core",
  "version": "1.0.0",
  "type": "commonjs",
  "scripts": {
    "barrel": "barrelsby --directory ./src --delete --singleQuotes && node ../../barrelsby-replace.js ./src/index.ts"
  }
}
```
I also have other projects and they also have a `package.json`, they're pretty much just the same as above

> and typedoc and other relevant project dependencies in there

I proceeded with this recommendation, and added this:
```json
  "devDependencies": {
    "typedoc": "0.23.28",
    "typescript": "4.9.5",
    "typedoc-theme-hierarchy": "3.1.0"
  }
```
After that, ran `pnpm nx run core:typedoc`. With this new setup, a warning arises while running it:
```
warning TypeDoc has been loaded multiple times. This is commonly caused by plugins which have their own installation of TypeDoc. The loaded paths are:
        D:\Software\Code\Active\nx-nyx\packages\core\node_modules\.pnpm\typedoc@0.23.28_typescript@4.9.5\node_modules\typedoc
        D:\Software\Code\Active\nx-nyx\node_modules\.pnpm\typedoc@0.23.28_typescript@4.9.5\node_modules\typedoc
Using TypeScript 4.9.5 from ./node_modules/.pnpm/typescript@4.9.5/node_modules/typescript/lib
```
However with this the problem isn't solved yet (it's still the same as the first sent image).

> take note of any configuration that is different in the project.json. I suspect the project.json ultimately indicates to which package.json to look at

I also took a look at what you mentioned here but these settings seem to be fine at least for me, here are the ones related to paths I could find on my core's `project.json`:
```json
  "sourceRoot": "packages/core/src",
  "rootDir": ".",
```

For now I'm using another theme that doesn't specify paths but the problem still limits me, I can't use some plugins or features that work with paths as described on the second comment. If there's anything I missed please let me know.

**Comment by mkhib** [comment]
Isn't it possible to config type doc in libraries that don't have a package.json and only have project.json ?

**Comment by Amgelo563** [comment]
> Isn't it possible to config type doc in libraries that don't have a package.json and only have project.json ?

Sorry but I don't understand what you mean, in my previous comment I mentioned that I do have in fact a package.json

**Comment by mkhib** [comment]
> > Isn't it possible to config type doc in libraries that don't have a package.json and only have project.json ?
> 
> Sorry but I don't understand what you mean, in my previous comment I mentioned that I do have in fact a package.json

Oh sorry for the confusion I was actually asking a question. I was trying to make this plugin work and I asked if it's possible to do it without adding project.json to every library because that's not something I want to do.

**Comment by AndrewRedican** [comment]
@Amgelo563,

Sorry. I don't provide support specific to typedoc itself or typedoc themes.

I have some follow-up questions:
+ Have you tried setting up the same typedoc configuration including the plugin outside the nx workspace to rule out whether it is something to do with Nx context or not?
+ You mentioned you are using another theme, and that seemed to work. Which plugin did not work, and which one did?
+ I have not made myself familiar with pnpm, but it seems that it is being installed twice, and probably the versions do not match perhaps?

I am only concerned with providing projects with sensible typedoc configuration defaults. If there is anything that jumps out that could be improved let me know. For instance,
+ Is the current typedoc plugin working on other/most projects or is it completely broken?
+ Do I need to provide more flexible configuration options?
+ Are there any additional checks that could be run to help prevent issues/headaches for some setups?
